language: node_js
node_js:
  - 'node'
  - '6'
  - '4'

deploy:
  on:
    branch: master
    node: 'node'
    tags: true
  provider: npm
  email: gurpreetatwal@users.noreply.github.com
  api_key: $NPM_TOKEN